name: Python Build and Artifact

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.2.2

    - name: Set up Python
      uses: actions/setup-python@v5.4.0
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest

    - name: Build package
      run: |
        python setup.py sdist bdist_wheel

    - name: Upload artifact
      uses: actions/upload-artifact@v4.6.0
      with:
        name: python-package
        path: dist/*
