name: Python Build and Artifact  # Name of the workflow

on: push  # Trigger the workflow on push events

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
    - name: Checkout code  # Step to checkout the repository code
      uses: actions/checkout@v4.2.2  # Use the checkout action version 4.2.2

    - name: Set up Python  # Step to set up Python environment
      uses: actions/setup-python@v5.4.0  # Use the setup-python action version 5.4.0
      with:
        python-version: '3.x'  # Specify the Python version to use

    - name: Install dependencies  # Step to install Python dependencies
      run: |
        python -m pip install --upgrade pip  # Upgrade pip to the latest version
        pip install -r requirements.txt  # Install dependencies from requirements.txt

    - name: Run tests  # Step to run tests
      run: |
        pytest  # Run tests using pytest

    - name: Build package  # Step to build the Python package
      run: |
        python setup.py sdist bdist_wheel  # Build source and wheel distribution

    - name: Upload artifact  # Step to upload the built package as an artifact
      uses: actions/upload-artifact@v4.6.0  # Use the upload-artifact action version 4.6.0
      with:
        name: python-package  # Name of the artifact
        path: dist/*  # Path to the built package files
